// Code generated by "stringer -type intColor -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[intColorRed-0]
	_ = x[intColorGreen-1]
	_ = x[intColorBlue-2]
	_ = x[intColorWhite-3]
	_ = x[intColorBlack-4]
}

const _intColor_name = "redgreenbluewhiteblack"

var _intColor_index = [...]uint8{0, 3, 8, 12, 17, 22}

func (i intColor) String() string {
	if i < 0 || i >= intColor(len(_intColor_index)-1) {
		return "intColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _intColor_name[_intColor_index[i]:_intColor_index[i+1]]
}
